name: IDX Login Automation

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    - cron: '0 * * * *'  # 每小时的 0 分执行
    - cron: '30 * * * *' # 每小时的 30 分执行

jobs:
  run-automation:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 运行器

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # 根据你的脚本兼容性选择合适的 Python 版本，例如 3.9, 3.10, 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # 假设你有一个 requirements.txt 文件
        # 如果没有 requirements.txt，可以直接安装 playwright 和 python-dotenv
        # pip install playwright python-dotenv requests

    - name: Install Playwright browsers
      run: playwright install --with-deps chromium # 安装 Chromium 及其依赖

    - name: Create empty cookie.json if not exists
      run: |
        if [ ! -f cookie.json ]; then
          echo '{"cookies": [], "origins": []}' > cookie.json
        fi
      # 确保 cookie.json 存在，即使是空的，以便脚本加载时不会出错

    - name: Run IDX Automation Script
      env:
        # 从 GitHub Secrets 获取 Telegram Token 和 Chat ID
        TG_TOKEN: ${{ secrets.TG_TOKEN }}
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        # APP_URL: https://idx.google.com # 如果你想覆盖脚本中的默认 APP_URL，可以在这里设置
      run: |
        python idx2.py

    - name: Upload Logs (Optional)
      if: always() # 无论脚本成功或失败，都上传日志
      uses: actions/upload-artifact@v4
      with:
        name: automation-logs
        path: |
          *.log
          *.txt
          *.png
          # 根据你的日志输出和截图文件命名习惯调整路径
